#!/bin/bash
# The host's own utility shaders (src/host/shaders/*.comp), compiled offline
# into checked-in headers of SPIR-V words, so the build needs no shader
# compiler. Run after editing a shader; needs glslc and spirv-val.
#   tools/build_shaders.sh
set -eu
cd "$(dirname "$0")/.."
for src in src/host/shaders/*.comp; do
    name=$(basename "$src" .comp)
    out=src/host/shaders/$name.spv.h
    tmp=$(mktemp)
    glslc -O --target-env=vulkan1.2 -o "$tmp.spv" "$src"
    spirv-val --target-env vulkan1.2 "$tmp.spv"
    glslc -O --target-env=vulkan1.2 -mfmt=num -o "$tmp" "$src"
    {
        echo "// Generated by tools/build_shaders.sh from $name.comp - do not edit."
        echo "#pragma once"
        echo "#include <cstdint>"
        echo "inline constexpr std::uint32_t k_${name}_spv[] = {"
        cat "$tmp"
        echo "};"
    } > "$out"
    rm -f "$tmp" "$tmp.spv"
    echo "$out: $(grep -o '0x' "$out" | wc -l) words"
done
