#!/usr/bin/env python3
"""Writes include/bbhost/params.hpp: a C++ struct for every param row type,
from the game's own definitions (dvdroot_ps4/paramdef/paramdef.paramdefbnd.dcx,
read with tools/bbparam.py), and one tag type per gameparam table.

    tools/gen_param_header.py [--app0 DIR] [-o include/bbhost/params.hpp]

Fields keep the game's internal names. Bitfields are C bitfields of the
field's own type, each unit padded to its end with an unnamed bitfield (SysV
would otherwise pack the next field into the unit's spare bytes), which both
the SysV and the Microsoft rules (mingw) lay out as the game does; every plain field's offset and every row's size is a static_assert,
so a header that does not match the definitions does not compile. Run again
only when the definitions change (they ship with the game; 1.09 is final).
"""
import argparse
import os
import re
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bbparam  # noqa: E402

CTYPE = {'s8': 'std::int8_t', 'u8': 'std::uint8_t', 'dummy8': 'std::uint8_t', 'fixstr': 'char',
         's16': 'std::int16_t', 'u16': 'std::uint16_t', 'fixstrW': 'char16_t',
         's32': 'std::int32_t', 'u32': 'std::uint32_t', 'f32': 'float'}
KEYWORDS = {'default', 'delete', 'new', 'class', 'register', 'template', 'typename', 'int', 'float', 'char',
            'short', 'long', 'unsigned', 'signed', 'auto', 'case', 'switch', 'return', 'this', 'operator',
            'private', 'public', 'protected', 'union', 'struct', 'enum', 'namespace', 'static', 'const'}


def ident(name):
    s = re.sub(r'[^A-Za-z0-9_]', '_', name) or 'field'
    if s[0].isdigit():
        s = '_' + s
    return s + '_' if s in KEYWORDS else s


def load_defs(app0):
    raw = bbparam.bnd4(bbparam.dcx(app0 + '/dvdroot_ps4/paramdef/paramdef.paramdefbnd.dcx'))
    defs = {}
    for _n, b in raw.items():
        try:
            count, fsize = struct.unpack_from('<HH', b, 0x08)
            if fsize != 0xd0:
                continue
            ptype, fields = bbparam.paramdef(b)
            at = struct.unpack_from('<Q', b, 0x30)[0]
            for i, f in enumerate(fields):
                o = at + i * fsize
                f['display'] = b[o:o + 0x40].decode('utf-16le', 'replace').split('\0')[0]
                f['enum'] = bbparam.cstr(b, o + 0x70, 0x20)
            defs[ptype] = fields
        except (struct.error, ValueError):
            pass
    return defs


def emit_struct(ptype, fields):
    out = ['struct %s {' % ident(ptype)]
    unit = None
    asserts, seen, unit = [], {}, None   # unit: [offset, bytes, used bits, ctype]
    size = 0

    def close():
        if unit and unit[2] < unit[1] * 8:
            out.append('    %s : %d;' % (unit[3], unit[1] * 8 - unit[2]))

    for f in fields:
        name = ident(f['name'])
        if name in seen:
            seen[name] += 1
            name = '%s_%d' % (name, seen[name])
        else:
            seen[name] = 0
        typ = CTYPE.get(f['type'], 'std::uint8_t')
        note = f.get('display', '')
        if f.get('enum') and f['enum'] != f['type']:
            note = (note + ' ' if note else '') + '[' + f['enum'] + ']'
        comment = ('  // ' + note.replace('\n', ' ').strip()) if note.strip() else ''
        if f['bits']:
            if not unit or unit[0] != f['offset']:
                close()
                unit = [f['offset'], f['bytes'], 0, typ]
            out.append('    %s %s : %d;%s' % (typ, name, f['bits'], comment))
            unit[2] += f['bits']
        else:
            close()
            unit = None
            es = bbparam.SIZES.get(f['type'], 1)
            n = f['bytes'] // es if es else f['bytes']
            if n > 1 or f['type'] in ('fixstr', 'fixstrW') or f['count'] > 1:
                out.append('    %s %s[%d];%s' % (typ, name, n, comment))
            else:
                out.append('    %s %s;%s' % (typ, name, comment))
            asserts.append('BB_OFFSET(%s, %s, 0x%x);' % (ident(ptype), name, f['offset']))
        size = max(size, f['offset'] + f['bytes'])
    close()
    out.append('};')
    asserts.append('BB_SIZE(%s, 0x%x);' % (ident(ptype), size))
    return out, asserts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--app0', default=bbparam.APP0)
    ap.add_argument('-o', default=os.path.join(os.path.dirname(__file__), '..', 'include', 'bbhost', 'params.hpp'))
    a = ap.parse_args()
    defs = load_defs(a.app0)
    tables = {}
    for name, raw in bbparam.bnd4(bbparam.dcx(a.app0 + '/dvdroot_ps4/param/gameparam/gameparam.parambnd.dcx')).items():
        if name.endswith('.param'):
            tables[name[:-len('.param')]] = bbparam.param_rows(raw)[0]
    lines = [
        '// Generated by tools/gen_param_header.py from the game\'s own param definitions',
        '// (dvdroot_ps4/paramdef/paramdef.paramdefbnd.dcx, Bloodborne 1.09). Do not edit.',
        '//',
        '// One struct per row type in namespace bb (bb::EQUIP_PARAM_WEAPON_ST - the',
        '// names bbhost/engine/param.hpp forward-declares), fields by the game\'s',
        '// internal names and in its order (comments: the definition\'s display name',
        '// and enum type). One tag per gameparam table in bb::params:',
        '// bb::params::EquipParamWeapon::Row is its row type and',
        '// ::name what BbHostApi::param_row takes, so a plugin writes',
        '//   auto* w = bb::param<bb::params::EquipParamWeapon>(api, 1000000);',
        '// (bbhost/sdk.hpp) and gets an EQUIP_PARAM_WEAPON_ST* into the live table.',
        '#pragma once',
        '',
        '#include "bbhost/engine/base.hpp"',
        '',
        'namespace bb {',
        '',
    ]
    used = sorted(set(tables.values()) & set(defs))
    asserts = []
    for t in sorted(defs):
        body, a2 = emit_struct(t, defs[t])
        lines += body + ['']
        asserts += a2
    lines += ['namespace detail::params_layout {'] + asserts + ['}  // namespace detail::params_layout', '',
                                                         '// The gameparam tables.', 'namespace params {', '']
    for name in sorted(tables, key=str.lower):
        t = tables[name]
        if t not in defs:
            lines.append('// %s: row type %s has no definition in the archive' % (name, t))
            continue
        lines.append('struct %s { using Row = %s; static constexpr const char* name = "%s"; };'
                     % (ident(name), ident(t), name))
    lines += ['', '}  // namespace params', '}  // namespace bb', '']
    with open(a.o, 'w') as f:
        f.write('\n'.join(lines))
    print('%s: %d row types (%d used by gameparam tables), %d tables' % (a.o, len(defs), len(used), len(tables)))


if __name__ == '__main__':
    main()
