#!/usr/bin/env python3
"""Generate src/engine/sixty_fps_sites.inc: the 60 FPS++ sites engine/frame_rate.cpp applies beyond its
own constant table, from Kyo's "60 FPS++" list for Bloodborne 1.09 (shadPS4's ps4_cheats,
PATCHES/Bloodborne.xml) and the eboot.

    tools/sixty_fps_sites.py Bloodborne.xml eboot-109-decrypted.bin > src/engine/sixty_fps_sites.inc

The list's lines are applied in order to a copy of the image (later lines overwrite earlier ones, as a
patch loader does), then every byte the list changes is kept except:
  - bytes engine/frame_rate.cpp's kSixtyConstants / kSixtyBytes already write;
  - the frame-time manager, 0x2434770..0x2435480 - ours replaces that function whole
    (its 60 mode is case 2 with no history, which is what those edits make of it);
  - EXCLUDE below, each with the reason.
Contiguous kept bytes become one site: its address, the bytes the eboot holds there, the bytes the list
leaves. frame_rate.cpp checks every site's old bytes before writing any.
"""
import struct
import sys
import xml.etree.ElementTree as ET

FRAME_MANAGER = (0x2434770, 0x2435480)
EXCLUDE = [
    # sub_2435630: a local's zeroing turned into a store of mode 2 into the flipper; ours picks the mode.
    (0x243565e, 0x2435666, 'frame mode'),
    # The frame modes' name table (debug display); absolute pointers valid only at the default load
    # address, and relocated at load, so not what the file holds.
    (0x575a920, 0x575a928, 'mode names'), (0x575a930, 0x575a938, 'mode names'),
    # The engine's timed condition wait returns at once instead of waiting: every job worker spins.
    # An emulator's latency workaround; the host's waits wake on time.
    (0x2483ec1, 0x2483ec6, 'timed wait'),
    # The sound thread's sleep, capped through a cave written over the tail of a live function
    # (sub_4632d0); frame_rate.cpp sets that thread's update time instead (MainThreadUpdateTime).
    (0x463300, 0x463312, 'sleep cave'), (0x2c0137d, 0x2c01382, 'sleep cave'),
    # The later list's version of that cap: the stub written into the loop itself (0x2c012cc).
    (0x2c012cc, 0x2c012de, 'sleep cave'),
    # The same loop's three profiling clock reads skipped: not needed with a host gettimeofday.
    (0x2c0118a, 0x2c0118c, 'profiling'), (0x2c011eb, 0x2c011ed, 'profiling'), (0x2c012ca, 0x2c012cc, 'profiling'),
]


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    root = ET.parse(sys.argv[1]).getroot()
    md = next(m for m in root.iter('Metadata') if m.attrib.get('Name') == '60 FPS++' and m.attrib.get('AppVer') == '01.09')
    eb = open(sys.argv[2], 'rb').read()
    phoff, phnum = struct.unpack_from('<Q', eb, 0x20)[0], struct.unpack_from('<H', eb, 0x38)[0]
    segs = []
    for i in range(phnum):
        t, fl, off, va, pa, fs, ms, al = struct.unpack_from('<IIQQQQQQ', eb, phoff + i * 56)
        if t == 1:
            segs.append((va + 0x400000, off, fs))

    def orig(a):
        for va, off, fs in segs:
            if va <= a < va + fs:
                return eb[off + a - va]
        raise SystemExit('0x%x is not in the image' % a)

    image = {}
    for line in md.find('PatchList'):
        a, ty, v = int(line.attrib['Address'], 16), line.attrib['Type'], line.attrib['Value']
        data = bytes.fromhex(v) if ty == 'bytes' else struct.pack('<I', int(v, 16)) if ty == 'bytes32' else None
        if data is None:
            raise SystemExit('line type %s' % ty)
        for k, b in enumerate(data):
            image[a + k] = b
    ours = set()
    src = open('src/engine/frame_rate.cpp').read()
    import re
    for m in re.finditer(r'\{0x([0-9a-f]+), 0x[0-9a-f]+, 0x[0-9a-f]+\}', src):
        ours.update(range(int(m.group(1), 16), int(m.group(1), 16) + 4))
    for m in re.finditer(r'\{0x([0-9a-f]+), (\d+), \{', src):
        ours.update(range(int(m.group(1), 16), int(m.group(1), 16) + int(m.group(2))))
    kept = sorted(a for a, b in image.items()
                  if b != orig(a) and a not in ours and not FRAME_MANAGER[0] <= a < FRAME_MANAGER[1]
                  and not any(lo <= a < hi for lo, hi, _ in EXCLUDE))
    # One site per run of changed bytes, joined across up to three unchanged bytes of the list's own
    # writes so a rewritten instruction stays whole.
    sites = []
    for a in kept:
        if sites and a - (sites[-1][0] + sites[-1][1]) <= 3 and all(x in image for x in range(sites[-1][0] + sites[-1][1], a)):
            sites[-1][1] = a - sites[-1][0] + 1
        else:
            sites.append([a, 1])
    print('// Generated by tools/sixty_fps_sites.py from Kyo\'s "60 FPS++" list for 1.09 (shadPS4 ps4_cheats,')
    print('// PATCHES/Bloodborne.xml) and the 1.09 eboot: address (Binary Ninja), old bytes, new bytes.')
    total = 0
    for a, n in sites:
        old = bytes(orig(a + k) for k in range(n))
        new = bytes(image.get(a + k, orig(a + k)) for k in range(n))
        total += n
        print('    {0x%08x, "%s", "%s"},' % (a, old.hex(), new.hex()))
    print('// %d sites, %d bytes' % (len(sites), total))


if __name__ == '__main__':
    main()
